name: Flutter CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - name: Opta Token Endpoint Test
        run: flutter test test/mackolik_visual_service.dart # Buraya token doğrulama testini yazacağız
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: flutter build apk --release
